### ISSUE TITLE
Haha are you serious? I learnt Perl a few years ago btw.

### ISSUE THREAD

**Issue by stephenwan** [GanHZ/Perl#1]

**Comment by GanHZ** [comment]
Cool! Good old days! It's been buried long enough. I think it might be a good time to dig it out and try another effort. What could be worse though? 😆

**Comment by stephenwan** [comment]
I would really recommend this book [High Order Perl](http://hop.perl.plover.com/book/) . Easy-to-read text but contains many techniques explained very clearly.
